### PR TITLE
Minor changes

### PR DESCRIPTION
**Pull request by katkamrachana**
-Hidden management tab in groups
-Show only draft or published status activities(i.e Pages, etc) in user dashboard
-Deleting courses from Course detail view
-On click on anywhere on template, if unit name is in edit mode, reset it
-Added login_reqd decorator to uDashboard so that an anonymous user cannot visit the dashboard of any user by link of username in card view or anywhere else.
-Redirect to course detail view from Course Authoring page (l.h.s)
-Expand the tree (collection_nav) in Course Detail

### CODE REVIEW

**Comment by kedar2a** [comment]
I think user dashboard should be public to anyone including anonymous user. So there is no need to add `@login_required` for the `uDashboard()`.

**Comment by katkamrachana** [comment]
When someone tries to access dashboard of any user, we fetch the requested
user's id and further fetching the author node of this user.

This is causing error if the request is coming from an anonymous user.
Hence, added the decorator.

On Thu, May 7, 2015 at 12:45 PM, Kedar Aitawdekar <notifications@github.com>
wrote:

> I think user dashboard should be public to anyone including anonymous
> user. So there is no need to add @login_required for the uDashboard().
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gnowledge/gstudio/pull/1152#issuecomment-99752487>.
>



-- 
Regards,
Rachana Katkam

**Comment by kedar2a** [comment]
For time being it's OK. But we need to fix it by any other way around.

**Comment by kedar2a** [comment]
The commit is satisfying all the listed behavior.

**Pull request merged**
