### PR TITLE
heterogenous collection sets default

### PR DESCRIPTION
**Pull request by supriyasawant**
while adding collection to the resources it asks for <code>"Heterogeneous or Homogeneous"</code> collection
but we don't have any way to store these information.

Now <code>"Heterogeneous"</code> collections sets as default while creating the collection.

<code>What to test:</code>
Try to set collections for any resource it will not ask for type of collection default it shows Heterogeneous collection.

### CODE REVIEW

**Comment by kedar2a** [comment]
- Now pop-up asking homogeneous and heterogeneous selection is not appearing. 
- But now **collection tab is not clickable** while **creating a new** page. It's clickable while editing existing page/file/gsystem.
- Tried in both the browser's: `Firefox` and `Chrome`

**Comment by supriyasawant** [comment]
1. error in collection tab resolved while creating new page
2. translations of ATs,GST,& RTs can be done via <b>Admin Designer</b>

Please run following command:
<code>python manage.py filldb</code>

What to test:
1. check while creating new page collection tab working properly
2. Go to Admin Designer & translate RTs or ATs or GST

**Comment by katkamrachana** [comment]
1. The issue stated by Kedar is fixed now. Collection tab is working as expected i.e not asking type of collection on creation.

2. Also, I translated a RT from admin designer and saved it. Where are these changes reflected? I checked in concept graph, but the modified RT is displayed in English. 

3. Please do remove the print statements from models.py

**Comment by kedar2a** [comment]
All seems good now!

**Pull request merged**
